(()=>{
'use strict';
const EVENT_SLUG='trd-la-regional-esmeralda';
const db=()=>window.__TRD_DB;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const statusLabel=s=>s==='approved'?'Aprobado':s==='rejected'?'Rechazado':s==='completed'?'Completado':s==='in_progress'?'En curso':'Pendiente';
let event=null;
async function getEvent(){if(event)return event;const {data}=await db().from('esmeralda_events').select('id').eq('slug',EVENT_SLUG).maybeSingle();event=data||null;return event}
async function isStaff(){const client=db();if(!client?.auth)return false;const {data:{session}}=await client.auth.getSession();if(!session?.user)return false;const {data}=await client.from('esmeralda_staff_roles').select('role').eq('user_id',session.user.id).maybeSingle();return !!data?.role}
function panel(){return $('#adminPanel')}
function shell(title,body){return `<div class="admin-toolbar"><div><h3>${title}</h3></div><button type="button" class="btn small outline" data-admin-fix="refresh">↻ Actualizar</button></div>${body}`}
async function overview(){const e=await getEvent();if(!e)return;const [{data:teams},{count:debaters}]=await Promise.all([db().from('esmeralda_teams').select('status').eq('event_id',e.id),db().from('esmeralda_debaters').select('id',{count:'exact',head:true})]);const all=teams||[];panel().innerHTML=shell('Resumen',`<div class="admin-grid"><div class="admin-card"><span>Equipos</span><strong>${all.length}</strong></div><div class="admin-card"><span>Pendientes</span><strong>${all.filter(x=>x.status==='pending').length}</strong></div><div class="admin-card"><span>Aprobados</span><strong>${all.filter(x=>x.status==='approved').length}</strong></div><div class="admin-card"><span>Rechazados</span><strong>${all.filter(x=>x.status==='rejected').length}</strong></div><div class="admin-card"><span>Debatientes</span><strong>${debaters||0}</strong></div></div>`)}
async function teams(){const e=await getEvent();if(!e)return;const {data,error}=await db().from('esmeralda_teams').select('id,team_name,school_name,district,status,created_at').eq('event_id',e.id).order('created_at',{ascending:false});if(error){panel().innerHTML=shell('Equipos',`<div class="empty">No se pudieron cargar los equipos.</div>`);return}panel().innerHTML=shell('Equipos',`<div class="table-wrap"><table class="data-table"><thead><tr><th>Equipo</th><th>Centro</th><th>Distrito</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${(data||[]).map(t=>`<tr><td><b>${esc(t.team_name)}</b></td><td>${esc(t.school_name||'—')}</td><td>${esc(t.district||'—')}</td><td>${statusLabel(t.status)}</td><td>${t.status!=='approved'?`<button type="button" class="btn small primary" data-admin-fix="approve" data-id="${t.id}">Aprobar</button>`:''} ${t.status!=='rejected'?`<button type="button" class="btn small danger" data-admin-fix="reject" data-id="${t.id}">Rechazar</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5">No hay equipos registrados.</td></tr>'}</tbody></table></div>`)}
async function rounds(){const e=await getEvent();if(!e)return;const {data,error}=await db().from('esmeralda_rounds').select('id,round_number,name,scheduled_at,status').eq('event_id',e.id).order('round_number');if(error){panel().innerHTML=shell('Rondas','<div class="empty">No se pudieron cargar las rondas.</div>');return}panel().innerHTML=shell('Rondas',`<form id="adminFixRoundForm" class="form-grid"><label>Número<input name="round_number" type="number" min="1" required></label><label>Nombre<input name="name" required placeholder="Ej. Ronda 1"></label><label>Fecha y hora<input name="scheduled_at" type="datetime-local"></label><label>Estado<select name="status"><option value="scheduled">Programada</option><option value="in_progress">En curso</option><option value="completed">Completada</option></select></label><button class="btn primary" type="submit">Crear ronda</button></form><div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Ronda</th><th>Fecha</th><th>Estado</th><th></th></tr></thead><tbody>${(data||[]).map(r=>`<tr><td>${r.round_number}</td><td>${esc(r.name)}</td><td>${r.scheduled_at?new Date(r.scheduled_at).toLocaleString('es-DO'): '—'}</td><td>${statusLabel(r.status)}</td><td><button type="button" class="btn small danger" data-admin-fix="delete-round" data-id="${r.id}">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="5">No hay rondas creadas.</td></tr>'}</tbody></table></div>`);$('#adminFixRoundForm')?.addEventListener('submit',async e2=>{e2.preventDefault();const fd=new FormData(e2.currentTarget);const {error:insertError}=await db().from('esmeralda_rounds').insert({event_id:e.id,round_number:Number(fd.get('round_number')),name:fd.get('name'),format:'debate',status:fd.get('status'),scheduled_at:fd.get('scheduled_at')?new Date(fd.get('scheduled_at')).toISOString():null});if(insertError)alert(insertError.message);else rounds()})}
async function announcements(){const e=await getEvent();if(!e)return;const {data,error}=await db().from('esmeralda_announcements').select('id,title,content,published,created_at').eq('event_id',e.id).order('created_at',{ascending:false});if(error){panel().innerHTML=shell('Anuncios','<div class="empty">No se pudieron cargar los anuncios.</div>');return}panel().innerHTML=shell('Anuncios',`<form id="adminFixAnnouncementForm" class="glass-form"><div class="form-grid"><label>Título<input name="title" required></label><label>Publicar<select name="published"><option value="false">No</option><option value="true">Sí</option></select></label></div><label>Contenido<textarea name="content" rows="4" required></textarea></label><button class="btn primary" type="submit">Crear anuncio</button></form><div class="table-wrap" style="margin-top:18px"><table class="data-table"><thead><tr><th>Título</th><th>Publicado</th><th></th></tr></thead><tbody>${(data||[]).map(a=>`<tr><td>${esc(a.title)}</td><td>${a.published?'Sí':'No'}</td><td><button type="button" class="btn small danger" data-admin-fix="delete-announcement" data-id="${a.id}">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="3">No hay anuncios.</td></tr>'}</tbody></table></div>`);$('#adminFixAnnouncementForm')?.addEventListener('submit',async e2=>{e2.preventDefault();const fd=new FormData(e2.currentTarget);const {error:insertError}=await db().from('esmeralda_announcements').insert({event_id:e.id,title:fd.get('title'),content:fd.get('content'),published:fd.get('published')==='true'});if(insertError)alert(insertError.message);else announcements()})}
async function load(name){if(!(await isStaff())||!panel())return;if(name==='overview')return overview();if(name==='teams')return teams();if(name==='rounds')return rounds();if(name==='announcements')return announcements()}
async function teamStatus(id,status){const {error}=await db().from('esmeralda_teams').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('No se pudo actualizar el equipo: '+error.message);return}await db().from('esmeralda_registrations').update({status,updated_at:new Date().toISOString()}).eq('team_id',id).eq('registration_type','team');await teams();if(typeof window.__TRDReloadParticipants==='function')window.__TRDReloadParticipants()}
function hideLegacy(){document.querySelectorAll('.admin-nav button').forEach(b=>{const text=b.textContent.trim().toLowerCase();if(text.includes('enfrentamientos')||text.includes('parejas'))b.remove()})}
function bind(){hideLegacy();document.addEventListener('click',async e=>{const nav=e.target.closest?.('.admin-nav button[data-panel]');if(nav){e.preventDefault();e.stopImmediatePropagation();const name=nav.dataset.panel;if(!['overview','teams','rounds','announcements'].includes(name))return;document.querySelectorAll('.admin-nav button').forEach(b=>b.classList.toggle('active',b===nav));await load(name);return}const action=e.target.closest?.('[data-admin-fix]');if(!action)return;const type=action.dataset.adminFix,id=action.dataset.id;if(type==='refresh')return load('overview');if(type==='approve')return teamStatus(id,'approved');if(type==='reject'){if(confirm('¿Confirmas que quieres rechazar este equipo?'))return teamStatus(id,'rejected')}if(type==='delete-round'){if(confirm('Eliminar esta ronda. ¿Continuar?')){const {error}=await db().from('esmeralda_rounds').delete().eq('id',id);if(error)alert(error.message);else rounds()}}if(type==='delete-announcement'){if(confirm('¿Eliminar este anuncio?')){const {error}=await db().from('esmeralda_announcements').delete().eq('id',id);if(error)alert(error.message);else announcements()}}},true)}
function boot(){if(!db())return setTimeout(boot,100);bind();hideLegacy();if($('#admin')&&!$('#admin').classList.contains('hidden'))load('overview')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
