(()=>{
  const LEGACY_APP='https://raw.githubusercontent.com/pegasus2314/actualizacion-de-la-pagina/d452a602318416ad2e818078ff27592284f148df/app.js';
  const baseCenters=[['17-01','09147','Politécnico Virginia Fidelina Matos de la Cruz'],['17-01','13388','Francisco Alberto Caamaño Deñó'],['17-01','04628','La Ceja'],['17-01','09196','Ángel María Santamaría'],['17-01','14367','Politécnico José de la Luz Guillén'],['17-01','13387','Politécnico José Reyes'],['17-01','09168','Politécnico General Eusebio Manzueta'],['17-01','09189','Politécnico Parroquial Sor Susana Daly – Centro de Promoción Rural'],['17-02','04522','Río Boyá'],['17-02','09121','Genaro Soriano Guzmán'],['17-02','04507','El Mamey'],['17-02','14234','Politécnico Ciudad del Conocimiento'],['17-02','05703','José Fco. Peña Gómez'],['17-02','09190','PROMAPEC'],['17-02','13164','Politécnico Julio Abreu Cuello'],['17-02','04740','Santa María'],['17-03','04543','Pedro Pimentel'],['17-03','04536','27 de Febrero'],['17-03','04561','General Gaspar Polanco'],['17-03','09126','Politécnico Morayma Veloz de Báez'],['17-03','14998','Centro Educativo en Artes Prof. Félix Rafael Nova'],['17-04','04714','Ana Virginia Reynoso'],['17-04','04583','Lorenzo Jiménez Santana'],['17-04','14726','Presbítero Carlos Nouel'],['17-04','09135','Lic. Yolanda Esther Rivera'],['17-04','09143','Gregorio Aybar Contreras'],['17-05','04665','Modesto Belén'],['17-05','09186','Hilario Vásquez de León'],['17-05','09185','Gregorio Luperón'],['17-05','09166','Rafael Castillo Reinoso']];
  const districts={'17-01':'Yamasá','17-02':'Monte Plata','17-03':'Bayaguana','17-04':'Sabana Grande de Boyá','17-05':'Peralvillo'};
  let centers=JSON.parse(localStorage.getItem('trd_centros')||'null')||baseCenters.slice();
  function loadLegacy(){if(document.querySelector('script[data-trd-legacy]')||window.__trdLegacyLoading)return;window.__trdLegacyLoading=true;const s=document.createElement('script');s.src=LEGACY_APP;s.dataset.trdLegacy='1';s.onload=()=>{window.__trdLegacyLoaded=true;initCenters()};s.onerror=()=>{const m=document.getElementById('loginMessage');if(m)m.textContent='No se pudo cargar el módulo principal del sistema.';initCenters()};document.head.appendChild(s)}
  function initCenters(){const nav=document.querySelector('.nav'),main=document.querySelector('main');if(!nav||!main)return;if(!nav.querySelector('[data-view="centros"]')){const a=document.createElement('a');a.href='#centros';a.dataset.view='centros';a.innerHTML='▦ <span>Centros</span>';nav.appendChild(a)}let section=document.getElementById('centros');if(!section){section=document.createElement('section');section.id='centros';section.className='section view-section view-hidden centros-view';section.innerHTML='<div class="section-heading"><span class="eyebrow">REGIONAL 17</span><h2>Centros educativos</h2><p>Consulta los centros registrados de la Regional 17.</p></div><div id="centrosGrid" class="centros-grid"></div>';main.appendChild(section)}const grid=document.getElementById('centrosGrid');if(grid)grid.innerHTML=centers.map(c=>`<article class="centro-card"><span>${c[0]} · ${districts[c[0]]}</span><small>${c[1]}</small><h3>${c[2]}</h3></article>`).join('')}
  function icons(){const style=document.createElement('style');style.textContent='.nav>a{display:inline-flex;align-items:center;gap:8px}.nav>a:first-child:before{content:"⌂"}.nav>a:nth-child(2):before{content:"▤"}.nav>a:nth-child(3):before{content:"♙"}.nav>a:nth-child(4):before{content:"◉"}.nav>a:nth-child(5):before{content:"⌖"}.nav>a:nth-child(6):before{content:"▦"}.nav>a:before{color:currentColor}.nav>a.active:before{color:var(--cyan)}#adminBtn{cursor:pointer!important;pointer-events:auto!important;position:relative!important;z-index:20!important}#loginDialog{z-index:9999!important}';document.head.appendChild(style);document.querySelectorAll('.nav>a').forEach(a=>{const n=a.firstChild;if(n&&n.nodeType===3&&/^[⌂▤♙◉⌖▦]/.test(n.textContent))n.textContent=n.textContent.replace(/^[⌂▤♙◉⌖▦]\s*/,'')})}
  function start(){icons();loadLegacy();setTimeout(initCenters,1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();