(()=>{
'use strict';
const SUPABASE_URL='https://bstdgcpakqmltifzaqso.supabase.co';
const SUPABASE_KEY='sb_publishable_-39OPIl11i5GSPBbF3q0ew_puLiVK7N';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const role=r=>r==='alternate'?'Suplente':'Debatiente';
const statusLabel=s=>s==='accredited'?'Acreditado':s==='rejected'?'Rechazado':'Pendiente';
const origin=location.href.split('#')[0].replace(/index\\.html?$/,'');
const qrUrl=id=>origin+'acreditacion.html?type=participant&id='+encodeURIComponent(id);
let eventId=null,adminAccess=false,loaded=false;

const style=document.createElement('style');
style.textContent=`
.participants-view-toolbar{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin:24px 0 16px;padding:15px 17px;border:1px solid rgba(182,231,255,.09);border-radius:15px;background:rgba(8,26,40,.58)}
.participants-view-toolbar strong{display:block;font:700 24px/1 'Barlow Condensed',sans-serif}.participants-view-toolbar small{display:block;margin-top:4px;color:#829ba9;font-size:11px}.participants-view-note{color:#8fa8b6;font-size:11px;text-align:right}
.participants-list{display:grid;gap:9px}.participant-row{display:grid;grid-template-columns:42px minmax(0,1fr) auto auto;align-items:center;gap:14px;padding:13px 15px;border:1px solid rgba(182,231,255,.09);border-radius:14px;background:linear-gradient(145deg,rgba(12,34,49,.94),rgba(7,23,35,.98));transition:.16s ease}.participant-row:hover{border-color:rgba(25,220,229,.24);transform:translateY(-1px)}
.participant-index{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;background:rgba(25,220,229,.065);border:1px solid rgba(25,220,229,.15);color:#19dce5;font:700 17px 'Barlow Condensed',sans-serif}.participant-main{min-width:0}.participant-main strong{display:block;font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.participant-main small{display:block;margin-top:4px;color:#829ba9;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.participant-team-name{color:#b9d0da}.participant-status{padding:6px 8px;border-radius:999px;font-size:9px;font-weight:800;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}.participant-status.pending{color:#d5c98b;background:rgba(213,201,139,.07);border:1px solid rgba(213,201,139,.14)}.participant-status.accredited{color:#9cf0c1;background:rgba(64,220,130,.08);border:1px solid rgba(64,220,130,.16)}.participant-status.rejected{color:#ff9a9a;background:rgba(255,90,90,.08);border:1px solid rgba(255,90,90,.16)}
.participant-qr{display:inline-flex;align-items:center;gap:6px;padding:8px 10px;border-radius:9px;border:1px solid rgba(25,220,229,.22);background:rgba(25,220,229,.055);color:#19dce5;font-size:10px;font-weight:800;cursor:pointer}.participant-qr:hover{background:rgba(25,220,229,.12)}
.qr-dialog-participant{border:0;padding:0;background:transparent}.qr-dialog-participant::backdrop{background:rgba(2,10,17,.78);backdrop-filter:blur(6px)}.qr-card-participant{position:relative;width:min(390px,calc(100vw - 26px));padding:27px;border:1px solid rgba(182,231,255,.14);border-radius:22px;background:#081a28;color:#eef8fb;text-align:center;box-shadow:0 28px 90px rgba(0,0,0,.5)}.qr-card-participant .qr-close{position:absolute;right:12px;top:9px;width:34px;height:34px;border:0;background:transparent;color:#9eb4c1;font-size:26px;cursor:pointer}.qr-card-participant h2{font:700 30px/1.05 'Barlow Condensed',sans-serif;margin:8px 0 4px}.qr-card-participant p{margin:0 0 17px;color:#8fa8b6;font-size:11px}.qr-code-participant{width:220px;height:220px;margin:0 auto 15px;padding:8px;background:#fff;border-radius:12px}.qr-code-participant canvas,.qr-code-participant img{display:block;width:100%!important;height:100%!important}.qr-card-participant small{display:block;color:#829ba9;font-size:10px;line-height:1.5}.qr-download{margin-top:16px}
@media(max-width:700px){.participants-view-toolbar{align-items:flex-start;flex-direction:column}.participants-view-note{text-align:left}.participant-row{grid-template-columns:36px minmax(0,1fr) auto}.participant-status{display:none}.participant-qr{grid-column:3;grid-row:1}.participant-index{width:34px;height:34px}}
`;
document.head.appendChild(style);

async function getEvent(){if(eventId)return eventId;const {data}=await db.from('esmeralda_events').select('id').eq('slug','trd-la-regional-esmeralda').maybeSingle();eventId=data?.id||null;return eventId}
async function checkAdmin(){const {data:{user}}=await db.auth.getUser();if(!user){adminAccess=false;return false}const {data,error}=await db.from('esmeralda_staff_roles').select('role').eq('user_id',user.id).in('role',['admin','admin_maestro','acreditacion','coordinador']).limit(1);adminAccess=!error&&!!data?.length;return adminAccess}
function qrModal(p){const d=document.createElement('dialog');d.className='qr-dialog-participant';const name=p.full_name||'Participante';d.innerHTML=`<div class="qr-card-participant"><button class="qr-close" type="button" aria-label="Cerrar">×</button><span class="eyebrow">QR DEL PARTICIPANTE</span><h2>${esc(name)}</h2><p>${esc(p.team_name||'Equipo sin nombre')}</p><div class="qr-code-participant"></div><small>Este código solo identifica al participante. La información privada se consulta únicamente después de iniciar sesión con permisos de acreditación.</small><div><button class="btn primary qr-download" type="button">Descargar QR</button></div></div>`;document.body.appendChild(d);d.querySelector('.qr-close').onclick=()=>{d.close();d.remove()};d.addEventListener('click',e=>{if(e.target===d){d.close();d.remove()}});d.showModal();const q=d.querySelector('.qr-code-participant');new QRCode(q,{text:qrUrl(p.id),width:220,height:220,correctLevel:QRCode.CorrectLevel.H});d.querySelector('.qr-download').onclick=()=>{const canvas=q.querySelector('canvas'),img=q.querySelector('img'),a=document.createElement('a');a.href=canvas?canvas.toDataURL('image/png'):img?.src||'';a.download='QR-'+name.replace(/[^a-z0-9áéíóúñü]+/gi,'-')+'.png';a.click()}}

async function render(){const grid=document.querySelector('#teamsGrid');if(!grid||location.hash.slice(1)!=='participantes')return;loaded=false;grid.className='participants-list';grid.innerHTML='<div class="empty">Cargando participantes…</div>';const eid=await getEvent();if(!eid){grid.innerHTML='<div class="empty">No hay un evento disponible.</div>';return}const {data,error}=await db.rpc('get_esmeralda_public_debaters',{p_event_id:eid});if(error){console.error('participants-view',error);grid.innerHTML='<div class="empty">No se pudieron cargar los participantes.</div>';return}const list=(data||[]).slice().sort((a,b)=>String(a.full_name||'').localeCompare(String(b.full_name||''),'es'));await checkAdmin();const section=document.querySelector('#participantes');const old=section?.querySelector('.participants-view-toolbar');old?.remove();if(section&&grid){const toolbar=document.createElement('div');toolbar.className='participants-view-toolbar';toolbar.innerHTML=`<div><strong>${list.length} ${list.length===1?'participante':'participantes'}</strong><small>Listado individual de los participantes de equipos aprobados.</small></div><div class="participants-view-note">${adminAccess?'Modo administrador · QR disponible':'Listado público · el QR está reservado al personal autorizado'}</div>`;section.querySelector('.section-heading')?.after(toolbar)}grid.innerHTML=list.length?list.map((p,i)=>`<article class="participant-row"><span class="participant-index">${i+1}</span><div class="participant-main"><strong>${esc(p.full_name||'Participante')}</strong><small><span class="participant-team-name">${esc(p.team_name||'Equipo sin nombre')}</span>${p.school_name?' · '+esc(p.school_name):''}${p.district?' · '+esc(p.district):''}</small></div><span class="participant-status ${p.accreditation_status||'pending'}">${statusLabel(p.accreditation_status)}</span>${adminAccess?`<button class="participant-qr" type="button" data-participant-qr="${esc(p.id)}">▣ QR</button>`:''}</article>`).join(''):'<div class="empty">Aún no hay participantes de equipos aprobados.</div>';loaded=true}

document.addEventListener('click',e=>{const b=e.target.closest('[data-participant-qr]');if(!b||!adminAccess)return;const p=(window.__trdParticipants||[]).find(x=>x.id===b.dataset.participantQr);if(p)qrModal(p)});
const observer=new MutationObserver(()=>{if(location.hash.slice(1)==='participantes'&&!loaded){const rows=[...document.querySelectorAll('#teamsGrid .participant-row')];if(!rows.length)render()}});observer.observe(document.body,{childList:true,subtree:true});
window.addEventListener('hashchange',()=>{if(location.hash.slice(1)==='participantes')setTimeout(render,0)});
(async()=>{await new Promise(r=>setTimeout(r,0));if(location.hash.slice(1)==='participantes')render()})();
})();